import { useMemo, useState } from 'react';
import { Coins, Landmark, PackageCheck, ScrollText, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';
import { EmptyState, FolioHeading, SectionHeader, StatusSeal } from '../../components/ui/LedgerUI';
import {
  BUILDING_CATALOG,
  MAGIC_ITEM_CATALOG,
  MARKET_CATALOG,
  MARKET_CATEGORIES,
  MILITARY_PURCHASES,
  RANSOM_VALUES,
  RETAINER_CATALOG,
  UNIVERSAL_AIDS,
  addEstate,
  addMagicItem,
  buyBuilding,
  buyMarketItem,
  collectImpost,
  collectTallage,
  collectUniversalAid,
  dismissRetainer,
  equipMagicItem,
  equipMarketEquipment,
  formatCoin,
  getMarketAvailability,
  hireRetainer,
  makeDeposit,
  payToFreeEnslavedPerson,
  performRetainerTask,
  purchaseMilitaryAsset,
  recordMagicItemUse,
  recordMajorInvestment,
  repayLoan,
  resolveFoodPriceCheck,
  resolveSpyExposure,
  sellMarketItem,
  settleRansom,
  takeLoan,
  toDeniers,
  trainMountForAttack,
  withdrawDeposit
} from '../../rules/economyRules';
import './EconomyLedger.css';

const TABS = [
  ['ledger','장부'],['market','시장'],['ransom','몸값'],['estate','토지와 건설'],['retinue','수행원'],['finance','금융과 원조'],['magic','마법 물품']
];
const Field = ({ label, children }) => <label className="economy-field"><span>{label}</span>{children}</label>;
const Coin = ({ value }) => <span className="economy-coin">{formatCoin(value)}</span>;

export default function EconomyLedger({ character, setCharacter }) {
  const economy = character.campaign?.economy;
  const [tab, setTab] = useState('ledger');
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [marketFilter, setMarketFilter] = useState({ category:'food',query:'',quantity:1,merchantSkill:'',merchantRoll:'',foodRoll:'',famine:false });
  const [emancipationForm, setEmancipationForm] = useState({amount:0.5,note:'',gmSpecial:false});
  const [ransomForm, setRansomForm] = useState({ status:'knight_vassal',amount:'',payer:'self',standingRoll:'' });
  const [estateForm, setEstateForm] = useState({ name:'',annualIncome:6,note:'',approved:false });
  const [buildingForm, setBuildingForm] = useState({ id:'manor_hall',quantity:1,lordApproval:false,estateId:'' });
  const [militaryForm, setMilitaryForm] = useState({ id:'bandits_10',quantity:1,lordApproval:false });
  const [retainerForm, setRetainerForm] = useState({ id:'steward',name:'',fundMagicResearch:false });
  const [taskForm, setTaskForm] = useState({ retainerId:'',skill:'',roll:'',modifier:0,note:'',gloryAmount:0,standingTarget:10,standingRoll:'',standingLabel:'' });
  const [loanForm, setLoanForm] = useState({ status:'knight_vassal',amount:1,lender:'',purpose:'',approved:false });
  const [depositForm, setDepositForm] = useState({ amount:1,institution:'',known:false,churchSuccess:false,feeRate:5 });
  const [investmentForm, setInvestmentForm] = useState({ amount:10,description:'',note:'' });
  const [aidForm, setAidForm] = useState({ id:'eldest_son_knighting',incomes:'6' });
  const [taxForm, setTaxForm] = useState({ amount:1,note:'',decision:false });
  const [magicQuery, setMagicQuery] = useState('');

  const execute = (operation, message) => {
    try {
      setError('');
      setCharacter(previous => operation(previous).character);
      setNotice(message);
    } catch (caught) {
      setNotice('');
      setError(caught.message || '경제 절차를 완료하지 못했습니다.');
    }
  };

  const marketItems = useMemo(() => MARKET_CATALOG.filter(item => item.category === marketFilter.category
    && (!marketFilter.query || item.label.toLowerCase().includes(marketFilter.query.toLowerCase()))), [marketFilter.category, marketFilter.query]);
  const magicItems = useMemo(() => MAGIC_ITEM_CATALOG.filter(item => !magicQuery || `${item.label} ${item.summary}`.toLowerCase().includes(magicQuery.toLowerCase())), [magicQuery]);
  const pendingRansoms = economy?.ransoms?.filter(claim => claim.status !== 'settled') || [];
  const activeEstates = economy?.estates?.filter(estate => estate.status === 'active') || [];
  const activeRetainers = economy?.retainers?.filter(retainer => retainer.status === 'active') || [];
  const taskRetainers = economy?.retainers?.filter(retainer => ['active','caught_pending_standing'].includes(retainer.status)) || [];
  const selectedTaskRetainer = taskRetainers.find(retainer => retainer.id === taskForm.retainerId);
  const ownedMagic = economy?.magicItems?.filter(item => !item.consumed) || [];

  const renderLedger = () => <>
    <section className="economy-summary" aria-label="재산 요약">
      <div><span>현금</span><strong><Coin value={economy?.coinDeniers || 0} /></strong></div>
      <div><span>장원</span><strong>{activeEstates.length}</strong></div>
      <div><span>미결 몸값</span><strong>{pendingRansoms.length}</strong></div>
      <div><span>대출 잔액</span><strong><Coin value={(economy?.loans || []).filter(item=>item.status==='active').reduce((sum,item)=>sum+Number(item.balanceDeniers||0),0)} /></strong></div>
      <div><span>수행원 연봉</span><strong><Coin value={activeRetainers.reduce((sum,item)=>sum+Number(item.annualCostDeniers||0),0)} /></strong></div>
    </section>
    <section className="economy-section"><SectionHeader index="I" title="최근 거래" meta="Liber Computi" />
      {(economy?.transactions || []).length ? <div className="economy-table-wrap"><table><thead><tr><th>연도</th><th>거래</th><th>근거</th><th>변화</th></tr></thead><tbody>{[...(economy.transactions || [])].reverse().slice(0,30).map(entry=><tr key={entry.id}><td>{entry.year}</td><td><strong>{entry.label}</strong>{entry.note&&<small>{entry.note}</small>}</td><td>{entry.sourcePage}</td><td className={entry.amountDeniers<0?'negative':entry.amountDeniers>0?'positive':''}>{entry.amountDeniers>0?'+':''}<Coin value={Math.abs(entry.amountDeniers)} /></td></tr>)}</tbody></table></div> : <EmptyState title="아직 거래가 없습니다">시장·몸값·겨울 정산의 모든 금전 이동이 이곳에 남습니다.</EmptyState>}
    </section>
    <section className="economy-section"><SectionHeader index="II" title="보유 물품" meta="Bona Mobilia" />
      {[...(economy?.equipment||[]),...(economy?.treasure||[])].filter(item=>!item.disposed&&Number(item.quantity)>0).length ? <div className="economy-table-wrap"><table><thead><tr><th>물품</th><th>수량</th><th>단가</th><th>처리</th></tr></thead><tbody>{['equipment','treasure'].flatMap(collection=>(economy?.[collection]||[]).filter(item=>!item.disposed&&Number(item.quantity)>0).map(item=><tr key={item.id}><td><strong>{item.label}</strong>{item.equipped&&<StatusSeal tone="active">장착</StatusSeal>}{item.attackTrained&&<StatusSeal tone="neutral">전투 훈련</StatusSeal>}</td><td>{item.quantity}</td><td><Coin value={item.unitValueDeniers}/></td><td><div className="economy-inline-actions">{collection==='equipment'&&<button type="button" className="text-command" onClick={()=>execute(value=>equipMarketEquipment(value,{inventoryId:item.id,equipped:!item.equipped}),item.equipped?'장착을 해제했습니다.':'전투 장비에 연결했습니다.')}>{item.equipped?'해제':'장착'}</button>}{item.category==='mount'&&!item.attackTrained&&<button type="button" className="text-command" onClick={()=>execute(value=>trainMountForAttack(value,{inventoryId:item.id}), '말값만큼을 추가 지불해 Phase 4 전투 훈련을 기록했습니다.')}>전투 훈련</button>}<button type="button" className="text-command" onClick={()=>execute(value=>sellMarketItem(value,{inventoryId:item.id,collection,quantity:1,merchantSkill:marketFilter.merchantSkill||undefined,merchantRoll:marketFilter.merchantRoll||undefined}), marketFilter.merchantRoll?'상인 Trade 판정 결과로 매각했습니다.':'시장 정가의 절반으로 매각했습니다.')}>시장 매각</button><button type="button" className="text-command" onClick={()=>execute(value=>sellMarketItem(value,{inventoryId:item.id,collection,quantity:1,tradeWithOwnLord:true}), '주군과 정가로 거래했습니다.')}>주군 거래</button></div></td></tr>))}</tbody></table></div> : <EmptyState title="기록된 소유 물품이 없습니다" />}
    </section>
  </>;

  const renderMarket = () => <section className="economy-section"><SectionHeader index="I" title="표준 가격표" meta="Standard Price List" />
    <div className="economy-toolbar"><Field label="분류"><select value={marketFilter.category} onChange={event=>setMarketFilter(previous=>({...previous,category:event.target.value}))}>{MARKET_CATEGORIES.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="검색"><input value={marketFilter.query} onChange={event=>setMarketFilter(previous=>({...previous,query:event.target.value}))} /></Field><Field label="수량"><input type="number" min="1" value={marketFilter.quantity} onChange={event=>setMarketFilter(previous=>({...previous,quantity:event.target.value}))}/></Field><Field label="상인 Trade"><input type="number" min="0" placeholder="선택" value={marketFilter.merchantSkill} onChange={event=>setMarketFilter(previous=>({...previous,merchantSkill:event.target.value}))}/></Field><Field label="상인 d20"><input type="number" min="1" max="20" placeholder="선택" value={marketFilter.merchantRoll} onChange={event=>setMarketFilter(previous=>({...previous,merchantRoll:event.target.value}))}/></Field></div>
    {marketFilter.category==='food'&&<div className="economy-toolbar"><Field label="식량 가격 d6"><input type="number" min="1" max="6" value={marketFilter.foodRoll} onChange={event=>setMarketFilter(previous=>({...previous,foodRoll:event.target.value}))}/></Field><label className="economy-check"><input type="checkbox" checked={marketFilter.famine} onChange={event=>setMarketFilter(previous=>({...previous,famine:event.target.checked}))}/><span>현재 연도 기근</span></label><button type="button" className="secondary-command" onClick={()=>execute(value=>resolveFoodPriceCheck(value,{roll:marketFilter.foodRoll||undefined,famine:marketFilter.famine}), '식량 가격 배수를 장부에 반영했습니다.')}>가격 판정</button><span className="economy-current-multiplier">현재 ×{economy?.famineMultiplier||1}</span></div>}
    <p className="economy-rule-line">도시에서는 현재 Phase에 열린 표준 품목을 표시 가격으로 삽니다. 외래품·참조품과 GM이 품절로 정한 물품은 자동 구매하지 않습니다. 상인을 쓰면 판정 결과에 따라 50%·75%·100%·150%가 적용됩니다.</p>
    <div className="economy-table-wrap"><table><thead><tr><th>품목</th><th>Phase</th><th>전투 자료</th><th>정가</th><th></th></tr></thead><tbody>{marketItems.map(item=>{const availability=getMarketAvailability(item.id,character.personal?.campaignYear);return <tr key={item.id}><td><strong>{item.label}</strong>{item.note&&<small>{item.note}</small>}</td><td>{item.phase||'시작'}{item.foreign&&' · 외래'}</td><td>{item.combat?Object.entries(item.combat).map(([key,value])=>`${key} ${value}`).join(' · '):'—'}</td><td><Coin value={item.costDeniers}/></td><td><button type="button" className="text-command" disabled={!availability.available||item.costDeniers===0} onClick={()=>execute(value=>buyMarketItem(value,{itemId:item.id,quantity:marketFilter.quantity,merchantSkill:marketFilter.merchantSkill||undefined,merchantRoll:marketFilter.merchantRoll||undefined}),`${item.label}을 장부에 올렸습니다.`)}>{availability.available?'구입':'입수 불가'}</button></td></tr>})}</tbody></table></div>
    <div className="economy-toolbar"><Field label="해방금 £"><input type="number" min="0.5" max="10" step="0.1" value={emancipationForm.amount} onChange={event=>setEmancipationForm(previous=>({...previous,amount:event.target.value}))}/></Field><Field label="해방 기록"><input value={emancipationForm.note} onChange={event=>setEmancipationForm(previous=>({...previous,note:event.target.value}))}/></Field><label className="economy-check"><input type="checkbox" checked={emancipationForm.gmSpecial} onChange={event=>setEmancipationForm(previous=>({...previous,gmSpecial:event.target.checked}))}/><span>£1½ 초과 특별 인물</span></label><button type="button" className="secondary-command" onClick={()=>execute(value=>payToFreeEnslavedPerson(value,{amountDeniers:toDeniers(emancipationForm.amount),note:emancipationForm.note,gmSpecial:emancipationForm.gmSpecial}), '소유가 아닌 해방 목적의 지불을 기록했습니다.')}>해방금 지불</button></div>
  </section>;

  const renderRansom = () => <>
    <section className="economy-section"><SectionHeader index="I" title="몸값 청구" meta="Ransom Claims" />
      <div className="economy-toolbar"><Field label="신분"><select value={ransomForm.status} onChange={event=>setRansomForm(previous=>({...previous,status:event.target.value,amount:''}))}>{Object.entries(RANSOM_VALUES).map(([id,[label,value]])=><option key={id} value={id}>{label} · {formatCoin(value)}</option>)}</select></Field><Field label="확정액 £"><input type="number" min="0" placeholder="최저액 자동" value={ransomForm.amount} onChange={event=>setRansomForm(previous=>({...previous,amount:event.target.value}))}/></Field><Field label="지급 주체"><select value={ransomForm.payer} onChange={event=>setRansomForm(previous=>({...previous,payer:event.target.value}))}><option value="self">본인</option><option value="lord">주군</option><option value="family">가문</option><option value="pledge">친구·서약</option></select></Field><Field label="Standing d20"><input type="number" min="1" max="20" value={ransomForm.standingRoll} onChange={event=>setRansomForm(previous=>({...previous,standingRoll:event.target.value}))}/></Field></div>
      {pendingRansoms.length?<div className="economy-claim-list">{pendingRansoms.map(claim=><div key={claim.id} className="economy-claim"><div><strong>{claim.direction==='payable'?'지급할 몸값':'받을 몸값'}</strong><span>{claim.year}년 · {claim.sourceId||claim.sourceType}</span></div><button type="button" className="primary-command" onClick={()=>execute(value=>settleRansom(value,{claimId:claim.id,ransomStatus:ransomForm.status,amountDeniers:ransomForm.amount?toDeniers(ransomForm.amount):undefined,payer:claim.direction==='payable'?ransomForm.payer:'captor',standingRoll:ransomForm.standingRoll||undefined}), '몸값을 정산하고 캠페인 장부에 반영했습니다.')}>정산</button></div>)}</div>:<EmptyState title="미결 몸값이 없습니다">Chapter 8에서 생긴 포로와 플레이어 몸값은 자동으로 이곳에 도착합니다.</EmptyState>}
    </section>
    <section className="economy-section"><SectionHeader index="II" title="Table 12-1" meta="Heribannum" /><div className="economy-table-wrap compact"><table><thead><tr><th>신분</th><th>최저 몸값</th></tr></thead><tbody>{Object.values(RANSOM_VALUES).map(([label,value])=><tr key={label}><td>{label}</td><td><Coin value={value}/></td></tr>)}</tbody></table></div></section>
  </>;

  const renderEstate = () => <>
    <section className="economy-section"><SectionHeader index="I" title="토지와 장원" meta="Terrae et Maneria" />
      <div className="economy-toolbar"><Field label="장원 이름"><input value={estateForm.name} onChange={event=>setEstateForm(previous=>({...previous,name:event.target.value}))}/></Field><Field label="평년 수입 £"><input type="number" min="0" value={estateForm.annualIncome} onChange={event=>setEstateForm(previous=>({...previous,annualIncome:event.target.value}))}/></Field><Field label="취득 근거"><input value={estateForm.note} onChange={event=>setEstateForm(previous=>({...previous,note:event.target.value}))}/></Field><label className="economy-check"><input type="checkbox" checked={estateForm.approved} onChange={event=>setEstateForm(previous=>({...previous,approved:event.target.checked}))}/><span>GM 수여·상속 승인</span></label><button type="button" className="primary-command" onClick={()=>execute(value=>addEstate(value,{name:estateForm.name,annualIncomeDeniers:toDeniers(estateForm.annualIncome),note:estateForm.note,gmApproved:estateForm.approved}), '장원을 영지 장부에 등록했습니다.')}>장원 등록</button></div>
      {activeEstates.length?<div className="economy-register-lines">{activeEstates.map(item=><div key={item.id}><strong>{item.name}</strong><span>평년 수입 <Coin value={item.annualIncomeDeniers}/> · {item.acquiredYear}년 취득</span></div>)}</div>:<EmptyState title="등록된 장원이 없습니다" />}
    </section>
    <section className="economy-section"><SectionHeader index="II" title="건설" meta="Construction" /><div className="economy-toolbar"><Field label="시설"><select value={buildingForm.id} onChange={event=>setBuildingForm(previous=>({...previous,id:event.target.value}))}>{BUILDING_CATALOG.map(item=><option key={item.id} value={item.id}>{item.label} · {formatCoin(item.costDeniers)}</option>)}</select></Field><Field label="수량·구역"><input type="number" min="1" value={buildingForm.quantity} onChange={event=>setBuildingForm(previous=>({...previous,quantity:event.target.value}))}/></Field><label className="economy-check"><input type="checkbox" checked={buildingForm.lordApproval} onChange={event=>setBuildingForm(previous=>({...previous,lordApproval:event.target.checked}))}/><span>방어시설 Standing [lord] 승인</span></label><button type="button" className="primary-command" onClick={()=>execute(value=>buyBuilding(value,{buildingId:buildingForm.id,quantity:buildingForm.quantity,lordApproval:buildingForm.lordApproval,estateId:buildingForm.estateId}), '건설비를 지출하고 시설을 등록했습니다.')}>건설</button></div>
      {(economy?.buildings||[]).length>0&&<div className="economy-register-lines">{economy.buildings.map(item=><div key={item.id}><strong>{item.label} × {item.quantity}</strong><span>{item.builtYear}년 · {item.dv?`DV ${item.dv} · `:''}<Coin value={item.costDeniers}/></span></div>)}</div>}
    </section>
    <section className="economy-section"><SectionHeader index="III" title="용병과 공성 장비" meta="Mercenarii" /><div className="economy-toolbar"><Field label="품목"><select value={militaryForm.id} onChange={event=>setMilitaryForm(previous=>({...previous,id:event.target.value}))}>{MILITARY_PURCHASES.map(item=><option key={item.id} value={item.id}>{item.label} · {formatCoin(item.costDeniers)}</option>)}</select></Field><Field label="수량"><input type="number" min="1" value={militaryForm.quantity} onChange={event=>setMilitaryForm(previous=>({...previous,quantity:event.target.value}))}/></Field><label className="economy-check"><input type="checkbox" checked={militaryForm.lordApproval} onChange={event=>setMilitaryForm(previous=>({...previous,lordApproval:event.target.checked}))}/><span>Standing [lord] 승인</span></label><button type="button" className="primary-command" onClick={()=>execute(value=>purchaseMilitaryAsset(value,{assetId:militaryForm.id,quantity:militaryForm.quantity,lordApproval:militaryForm.lordApproval}), '전쟁 물자를 장부에 올렸습니다.')}>구입</button></div></section>
  </>;

  const renderRetinue = () => <>
    <section className="economy-section"><SectionHeader index="I" title="전문 수행원" meta="Personae Speciales" />
      <div className="economy-toolbar"><Field label="직책"><select value={retainerForm.id} onChange={event=>setRetainerForm(previous=>({...previous,id:event.target.value}))}>{RETAINER_CATALOG.map(item=><option key={item.id} value={item.id}>{item.label}{item.phase?` · Phase ${item.phase}`:''}</option>)}</select></Field><Field label="이름"><input value={retainerForm.name} onChange={event=>setRetainerForm(previous=>({...previous,name:event.target.value}))}/></Field>{retainerForm.id==='magician'&&<label className="economy-check"><input type="checkbox" checked={retainerForm.fundMagicResearch} onChange={event=>setRetainerForm(previous=>({...previous,fundMagicResearch:event.target.checked}))}/><span>연간 연구비 지급</span></label>}<button type="button" className="primary-command" onClick={()=>execute(value=>hireRetainer(value,{retainerId:retainerForm.id,name:retainerForm.name,fundMagicResearch:retainerForm.fundMagicResearch}), '전문 수행원을 고용했습니다.')}>고용</button></div>
      <p className="economy-rule-line">연봉은 보통 1인당 £1이며 같은 만큼 연간 Glory를 제공합니다. 비마술사 기술은 Winter에 자동 경험 판정합니다. 해고는 한 해 급료 또는 Honor 1이 필요합니다.</p>
      {taskRetainers.length?<div className="economy-table-wrap"><table><thead><tr><th>수행원</th><th>기술</th><th>연봉</th><th></th></tr></thead><tbody>{taskRetainers.map(item=>{const last=(item.tasks||[]).filter(task=>task.year===character.personal?.campaignYear).at(-1);return <tr key={item.id}><td><strong>{item.name}</strong><small>{item.label} · {item.age}세{item.status==='caught_pending_standing'?' · 발각됨':''}</small></td><td>{Object.entries(item.skills||{}).map(([key,value])=>`${key} ${value}`).join(' · ')||'일반 종자 절차'}{last&&<small>최근: d20 {last.roll}/{last.target} · {last.outcome} · {last.effect||last.note}</small>}</td><td><Coin value={item.annualCostDeniers}/></td><td>{item.status==='active'&&<><button type="button" className="text-command" onClick={()=>execute(value=>dismissRetainer(value,{retainerId:item.id}), '한 해 급료를 지급하고 해고했습니다.')}>급료 후 해고</button><button type="button" className="text-command" onClick={()=>execute(value=>dismissRetainer(value,{retainerId:item.id,loseHonor:true}), 'Honor 1을 잃고 해고했습니다.')}>Honor로 해고</button></>}</td></tr>})}</tbody></table></div>:<EmptyState title="고용한 전문 수행원이 없습니다" />}
    </section>
    <section className="economy-section"><SectionHeader index="II" title="수행원 임무" meta="Officia Retinentium" />
      <div className="economy-toolbar"><Field label="수행원"><select value={taskForm.retainerId} onChange={event=>{const retainer=taskRetainers.find(item=>item.id===event.target.value);setTaskForm(previous=>({...previous,retainerId:event.target.value,skill:Object.keys(retainer?.skills||{})[0]||''}));}}><option value="">선택</option>{taskRetainers.map(item=><option key={item.id} value={item.id}>{item.name} · {item.label}</option>)}</select></Field>{selectedTaskRetainer?.status==='caught_pending_standing'?<><Field label="Standing 이름"><input value={taskForm.standingLabel} onChange={event=>setTaskForm(previous=>({...previous,standingLabel:event.target.value}))}/></Field><Field label="Standing 값"><input type="number" min="0" value={taskForm.standingTarget} onChange={event=>setTaskForm(previous=>({...previous,standingTarget:event.target.value}))}/></Field><Field label="d20"><input type="number" min="1" max="20" value={taskForm.standingRoll} onChange={event=>setTaskForm(previous=>({...previous,standingRoll:event.target.value}))}/></Field><button type="button" className="primary-command" onClick={()=>execute(value=>resolveSpyExposure(value,{retainerId:taskForm.retainerId,standingLabel:taskForm.standingLabel,standingTarget:taskForm.standingTarget,roll:taskForm.standingRoll,note:taskForm.note}), '첩자 발각 후 Standing 결과를 기록했습니다.')}>발각 해결</button></>:<><Field label="기술"><select value={taskForm.skill} disabled={!selectedTaskRetainer} onChange={event=>setTaskForm(previous=>({...previous,skill:event.target.value}))}>{Object.keys(selectedTaskRetainer?.skills||{}).map(skill=><option key={skill} value={skill}>{skill}</option>)}</select></Field><Field label="d20"><input type="number" min="1" max="20" value={taskForm.roll} onChange={event=>setTaskForm(previous=>({...previous,roll:event.target.value}))}/></Field><Field label="상황 수정"><input type="number" value={taskForm.modifier} onChange={event=>setTaskForm(previous=>({...previous,modifier:event.target.value}))}/></Field>{selectedTaskRetainer?.profileId==='herald'&&<Field label="원래 Glory"><input type="number" min="0" value={taskForm.gloryAmount} onChange={event=>setTaskForm(previous=>({...previous,gloryAmount:event.target.value}))}/></Field>}<Field label="임무"><input value={taskForm.note} onChange={event=>setTaskForm(previous=>({...previous,note:event.target.value}))}/></Field><button type="button" className="primary-command" disabled={!selectedTaskRetainer||!taskForm.roll} onClick={()=>execute(value=>performRetainerTask(value,{retainerId:taskForm.retainerId,skill:taskForm.skill,roll:taskForm.roll,modifier:taskForm.modifier,note:taskForm.note,gloryAmount:taskForm.gloryAmount}), '수행원 임무 결과를 기록했습니다.')}>임무 판정</button></>}</div>
      <p className="economy-rule-line">대장장이는 연 1회 검을 만들고, 음유시인은 연 1회 구혼 판정을 대신하며, 첩자는 연 3회 임무를 수행합니다. 첩자 성공은 관련 후속 판정 +5, 대실패는 발각 후 GM이 지정한 Standing 판정을 요구합니다.</p>
    </section>
  </>;

  const renderFinance = () => <>
    <section className="economy-section"><SectionHeader index="I" title="대출" meta="Mutuum" /><div className="economy-toolbar"><Field label="신분·한도"><select value={loanForm.status} onChange={event=>setLoanForm(previous=>({...previous,status:event.target.value}))}>{Object.entries(RANSOM_VALUES).map(([id,[label,value]])=><option key={id} value={id}>{label} · {formatCoin(value)}</option>)}</select></Field><Field label="금액 £"><input type="number" min="0" value={loanForm.amount} onChange={event=>setLoanForm(previous=>({...previous,amount:event.target.value}))}/></Field><Field label="대주"><input value={loanForm.lender} onChange={event=>setLoanForm(previous=>({...previous,lender:event.target.value}))}/></Field><Field label="목적"><input value={loanForm.purpose} onChange={event=>setLoanForm(previous=>({...previous,purpose:event.target.value}))}/></Field><label className="economy-check"><input type="checkbox" checked={loanForm.approved} onChange={event=>setLoanForm(previous=>({...previous,approved:event.target.checked}))}/><span>선하거나 기독교적 목적</span></label><button type="button" className="primary-command" onClick={()=>execute(value=>takeLoan(value,{status:loanForm.status,amountDeniers:toDeniers(loanForm.amount),lender:loanForm.lender,purpose:loanForm.purpose,goodOrChristianPurpose:loanForm.approved}), '대출을 받고 장부에 채무를 기록했습니다.')}>대출</button></div>
      <p className="economy-rule-line">연 이자는 대출 시점의 Phase × 10%이며 통상 자신의 Heribannum까지 빌릴 수 있습니다.</p>{(economy?.loans||[]).filter(item=>item.status==='active').map(item=><div key={item.id} className="economy-finance-row"><div><strong>{item.lender}</strong><span>잔액 <Coin value={item.balanceDeniers}/> · 연 {Math.round(item.annualRate*100)}%</span></div><button type="button" className="text-command" onClick={()=>execute(value=>repayLoan(value,{loanId:item.id,amountDeniers:item.balanceDeniers}), '대출을 전액 상환했습니다.')}>전액 상환</button></div>)}</section>
    <section className="economy-section"><SectionHeader index="II" title="수도원 예금" meta="Depositum" /><div className="economy-toolbar"><Field label="금액 £"><input type="number" min="0" value={depositForm.amount} onChange={event=>setDepositForm(previous=>({...previous,amount:event.target.value}))}/></Field><Field label="기관"><input value={depositForm.institution} onChange={event=>setDepositForm(previous=>({...previous,institution:event.target.value}))}/></Field><Field label="연 수수료 %"><input type="number" min="5" max="10" value={depositForm.feeRate} onChange={event=>setDepositForm(previous=>({...previous,feeRate:event.target.value}))}/></Field><label className="economy-check"><input type="checkbox" checked={depositForm.known} onChange={event=>setDepositForm(previous=>({...previous,known:event.target.checked}))}/><span>수도원장과 친분</span></label><label className="economy-check"><input type="checkbox" checked={depositForm.churchSuccess} onChange={event=>setDepositForm(previous=>({...previous,churchSuccess:event.target.checked}))}/><span>Standing [Church] 성공</span></label><button type="button" className="primary-command" onClick={()=>execute(value=>makeDeposit(value,{amountDeniers:toDeniers(depositForm.amount),institution:depositForm.institution,personallyKnownToAbbot:depositForm.known,churchStandingSuccess:depositForm.churchSuccess,feeRate:Number(depositForm.feeRate)/100}), '수도원에 예치했습니다.')}>예치</button></div>{(economy?.deposits||[]).filter(item=>item.status==='active').map(item=><div key={item.id} className="economy-finance-row"><div><strong>{item.institution}</strong><span>잔액 <Coin value={item.balanceDeniers}/> · 연 수수료 {Math.round(item.annualFeeRate*100)}%</span></div><button type="button" className="text-command" onClick={()=>execute(value=>withdrawDeposit(value,{depositId:item.id,amountDeniers:item.balanceDeniers}), '예금을 전액 인출했습니다.')}>전액 인출</button></div>)}</section>
    <section className="economy-section"><SectionHeader index="III" title="대규모 지출과 원조" meta="Auxilia" /><div className="economy-toolbar"><Field label="투자액 £"><input type="number" min="0" value={investmentForm.amount} onChange={event=>setInvestmentForm(previous=>({...previous,amount:event.target.value}))}/></Field><Field label="투자 대상"><input value={investmentForm.description} onChange={event=>setInvestmentForm(previous=>({...previous,description:event.target.value}))}/></Field><button type="button" className="secondary-command" onClick={()=>execute(value=>recordMajorInvestment(value,{amountDeniers:toDeniers(investmentForm.amount),description:investmentForm.description,note:investmentForm.note}), '대규모 지출을 기록했습니다.')}>지출 기록</button></div><p className="economy-rule-line">Chapter 12는 투자 수익률을 주지 않습니다. 따라서 지출과 대상만 기록하며 수익을 만들지 않습니다.</p>
      <div className="economy-toolbar"><Field label="보편적 원조"><select value={aidForm.id} onChange={event=>setAidForm(previous=>({...previous,id:event.target.value}))}>{UNIVERSAL_AIDS.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="봉신별 평년 수입 £"><input value={aidForm.incomes} placeholder="6, 6, 9" onChange={event=>setAidForm(previous=>({...previous,incomes:event.target.value}))}/></Field><button type="button" className="secondary-command" onClick={()=>execute(value=>collectUniversalAid(value,{aidId:aidForm.id,vassalAnnualIncomesDeniers:aidForm.incomes.split(',').map(item=>toDeniers(item.trim()))}), '보편적 원조를 한 번 징수했습니다.')}>원조 징수</button></div>
      <div className="economy-toolbar"><Field label="세액 £"><input type="number" min="0" value={taxForm.amount} onChange={event=>setTaxForm(previous=>({...previous,amount:event.target.value}))}/></Field><Field label="결정 근거"><input value={taxForm.note} onChange={event=>setTaxForm(previous=>({...previous,note:event.target.value}))}/></Field><label className="economy-check"><input type="checkbox" checked={taxForm.decision} onChange={event=>setTaxForm(previous=>({...previous,decision:event.target.checked}))}/><span>궁정·시민 결정 기록</span></label><button type="button" className="secondary-command" onClick={()=>execute(value=>collectTallage(value,{amountDeniers:toDeniers(taxForm.amount),note:taxForm.note,gmDecision:taxForm.decision}), '동의된 특별세를 기록했습니다.')}>Tallage</button><button type="button" className="secondary-command" onClick={()=>execute(value=>collectImpost(value,{amountDeniers:toDeniers(taxForm.amount),note:taxForm.note}), '강제 부과금과 Commoners Standing -2를 반영했습니다.')}>Impost</button></div>
    </section>
  </>;

  const renderMagic = () => <>
    <section className="economy-section"><SectionHeader index="I" title="보유 마법 물품" meta="Res Incantatae" />{ownedMagic.length?<div className="economy-table-wrap"><table><thead><tr><th>물품</th><th>상태</th><th>효과</th><th></th></tr></thead><tbody>{ownedMagic.map(owned=>{const profile=MAGIC_ITEM_CATALOG.find(item=>item.id===owned.magicItemId);return <tr key={owned.id}><td><strong>{owned.label}</strong><small>{owned.acquiredYear}년 · {owned.acquisition}</small></td><td>{owned.equipped?'착용 중':owned.used?`${owned.useCount}회 사용`:'보관'}</td><td>{profile?.summary}{owned.magicItemId==='ring_protection'&&<label className="economy-inline-select"><span>보호 원인</span><select value={owned.protectionChoice||''} onChange={event=>execute(value=>equipMagicItem(value,{ownedItemId:owned.id,equipped:owned.equipped,protectionChoice:event.target.value}), '보호 반지의 피해 원인을 기록했습니다.')}><option value="">선택</option><option value="steel">강철</option><option value="fire">불</option><option value="drowning">익사</option></select></label>}{owned.magicItemId==='holy_relic_amulet'&&<label className="economy-inline-select"><span>선택 특성</span><select value={owned.religiousTrait||''} onChange={event=>execute(value=>equipMagicItem(value,{ownedItemId:owned.id,equipped:owned.equipped,religiousTrait:event.target.value}), '성유물 부적의 종교 특성을 기록했습니다.')}><option value="">선택</option><option value="chaste">Chaste</option><option value="forgiving">Forgiving</option><option value="merciful">Merciful</option><option value="modest">Modest</option><option value="temperate">Temperate</option><option value="trusting">Trusting</option></select></label>}</td><td><div className="economy-inline-actions"><button type="button" className="text-command" onClick={()=>execute(value=>equipMagicItem(value,{ownedItemId:owned.id,equipped:!owned.equipped,protectionChoice:owned.protectionChoice,religiousTrait:owned.religiousTrait}),owned.equipped?'마법 물품 장착을 해제했습니다.':'마법 효과를 활성화했습니다.')}>{owned.equipped?'해제':'장착'}</button><button type="button" className="text-command" onClick={()=>execute(value=>recordMagicItemUse(value,{ownedItemId:owned.id,outcome:'플레이 중 효과 처리',consume:Boolean(profile?.effects?.singleUse||profile?.effects?.consumable)}), '사용 결과를 기록했습니다.')}>사용 기록</button></div></td></tr>})}</tbody></table></div>:<EmptyState title="보유한 마법 물품이 없습니다">마법 물품은 시장에서 살 수 없으며 모험·선물·시련으로만 등록합니다.</EmptyState>}</section>
    <section className="economy-section"><SectionHeader index="II" title="Chapter 12 목록" meta="Catalogus Magicus" /><Field label="목록 검색"><input value={magicQuery} onChange={event=>setMagicQuery(event.target.value)}/></Field><div className="economy-magic-list">{magicItems.map(item=><details key={item.id}><summary><span><strong>{item.label}</strong><small>{item.kind}</small></span></summary><p>{item.summary}</p><button type="button" className="text-command" onClick={()=>execute(value=>addMagicItem(value,{magicItemId:item.id,acquisition:'adventure',note:'GM이 확인한 모험 획득'}),`${item.label}을 보물 장부에 등록했습니다.`)}>획득 기록</button><small>{item.sourcePage} · {Object.keys(item.effects).join(', ')}</small></details>)}</div></section>
  </>;

  return <article className="folio-page economy-ledger view-animate">
    <FolioHeading eyebrow="Capitulum XII · Wealth and Treasure" title="재산과 보물" year={character.personal?.campaignYear}>동전, 영지, 채무와 전리품을 하나의 장부에서 처리합니다.</FolioHeading>
    <div className="economy-tabs" role="tablist" aria-label="경제 장부 구역">{TABS.map(([id,label])=><button key={id} type="button" role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {error&&<div className="economy-message economy-message--error" role="alert"><ShieldCheck size={17} aria-hidden="true"/>{error}</div>}
    {notice&&<div className="economy-message" role="status"><PackageCheck size={17} aria-hidden="true"/>{notice}</div>}
    {tab==='ledger'&&renderLedger()}{tab==='market'&&renderMarket()}{tab==='ransom'&&renderRansom()}{tab==='estate'&&renderEstate()}{tab==='retinue'&&renderRetinue()}{tab==='finance'&&renderFinance()}{tab==='magic'&&renderMagic()}
    <footer className="economy-colophon"><Coins size={16} aria-hidden="true"/><span>£1 = 20s = 240d</span><Landmark size={16} aria-hidden="true"/><span>장원은 면적이 아니라 경제 단위입니다.</span><UsersRound size={16} aria-hidden="true"/><span>가신 생활비는 현금 지급이 아닌 현물 유지입니다.</span><Sparkles size={16} aria-hidden="true"/><span>마법 물품은 시장에서 거래하지 않습니다.</span><ScrollText size={16} aria-hidden="true"/><span>원문 193-209쪽</span></footer>
  </article>;
}
